language: php

php:
  - 7.4
  - 8.0
  - 8.1

env:
  global:
    - PATH=$PATH:/home/travis/.config/composer/vendor/bin
    - TRAVIS_NODE_VERSION="4.0.0"
  matrix:
    - DRUPAL_VERSION=9
    - DRUPAL_VERSION=10

# Enable Travis containers.
sudo: false

services:
  - mysql

install:
  - composer self-update
  - composer require --no-interaction --dev --no-update drupal/core-recommended:^${DRUPAL_VERSION} drupal/core-composer-scaffold:^${DRUPAL_VERSION}
  - composer install
  # Pin node version.
  # @see http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
  # Set sendmail so Drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - mysql -e 'create database drupal'
  # Install Drupal.
  - ./vendor/bin/drush --yes --root=$PWD/drupal site-install --db-url=mysql://travis:@127.0.0.1/drupal --debug
  # Copy the static HTML that is used for blackbox testing in the web root.
  - cp -r fixtures/blackbox $PWD/drupal
  # Copy our test module to the correct location.
  - cp -r fixtures/drupal/modules/behat_test drupal/modules
  - ./vendor/bin/drush --yes --root=$PWD/drupal en behat_test
  # Disable the page cache.
  - ./vendor/bin/drush --yes --root=$PWD/drupal pmu page_cache
  # Test with big_pipe enabled.
  - ./vendor/bin/drush --yes --root=$PWD/drupal en -y big_pipe
  # Clear the cache on Drupal 6 and 7, rebuild on Drupal 8.
  - ./vendor/bin/drush --debug runserver :8888 > ~/debug.txt 2>&1 &
  - sleep 4s

script:
  - composer test
  - npm test
  - vendor/bin/behat -fprogress --strict
  - vendor/bin/behat -fprogress --profile=drupal${DRUPAL_VERSION} --strict

after_failure:
  - cat ~/debug.txt
