parameters:
  # This overrides the class for the core version of this class
  behat.definition.proposal.annotated.class: Drupal\DrupalExtension\Definition\Proposal\AnnotatedDefinitionProposal

  # Context initializer.
  drupal.drupal_extension.context.initializer.class: Drupal\DrupalExtenstion\Context\Initializer\DrupalAwareInitializer

  drupal.drupal_extension.basic_auth:
    username: ~
    password: ~
  drupal.drupal_extension.drush_alias: ~

services:
  drupal.drupal_extension.context:
    class: Drupal\DrupalExtension\Context\DrupalContext
    initializer:
      class: %drupal.drupal_extension.context.initializer.class%
      tags:
        - { name: behat.context.initializer }
