parameters:
  # This overrides the class for the core version of this class
  behat.definition.proposal.annotated.class: Drupal\DrupalExtension\Definition\Proposal\AnnotatedDefinitionProposal

  behat.drupal.basic_auth:
    username: ~
    password: ~
  behat.drupal.drush_alias: ~

services:
